import pymongo
import os
from dotenv import load_dotenv

load_dotenv()

DB_USER = os.getenv("MONGO_USER", default="OOPS")
DB_PASSWORD = os.getenv("MONGO_PASSWORD", default="OOPS")
CLUSTER_NAME = os.getenv("MONGO_CLUSTER_NAME", default="OOPS")

connection_uri = f"mongodb+srv://{DB_USER}:{DB_PASSWORD}@{CLUSTER_NAME}.mongodb.net/test?retryWrites=true&w=majority"
print("----------------")
print("URI:", connection_uri)

client = pymongo.MongoClient(connection_uri)
print("----------------")
print("CLIENT:", type(client), client)

db = client.rpg_database  # "test_database" or whatever you want to call it
print("----------------")
print("DB:", type(db), db)

collection = db.rpg  # "pokemon_test" or whatever you want to call it
print("----------------")
print("COLLECTION:", type(collection), collection)

print("----------------")
print("COLLECTIONS:")
print(db.list_collection_names())

character_table = [
  {
    "character_id": 1,
    "name": "Aliquid iste optio reiciendi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 2,
    "name": "Optio dolorem ex a",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 3,
    "name": "Minus c",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 4,
    "name": "Sit ut repr",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 5,
    "name": "At id recusandae expl",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 6,
    "name": "Non nobis et of",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 7,
    "name": "Perferendis",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 8,
    "name": "Accusantium amet quidem eve",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 9,
    "name": "Sed nostrum inventore error m",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 10,
    "name": "Harum repellendus omnis od",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 11,
    "name": "Itaque ut commodi,",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 12,
    "name": "Molestiae quis",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 13,
    "name": "Ali",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 14,
    "name": "Tempora quod optio possimus il",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 15,
    "name": "Sed itaque beatae pari",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 16,
    "name": "Quam dolor",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 17,
    "name": "Molestias expedita",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 18,
    "name": "Lauda",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 19,
    "name": "Incidunt sint perferen",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 20,
    "name": "Laboriosa",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 21,
    "name": "Dolore esse nesciunt fugit com",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 22,
    "name": "Dolorum nam reic",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 23,
    "name": "Repellat ad numquam volu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 24,
    "name": "Facere enim velit eligend",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 25,
    "name": "Sed ratione quis rep",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 26,
    "name": "Doloribus neque",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 27,
    "name": "Ab voluptas se",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 28,
    "name": "Molestias m",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 29,
    "name": "In pariatur corpori",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 30,
    "name": "Possimus ad dignissimos vel, a",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 31,
    "name": "At minus accusa",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 32,
    "name": "Ad necess",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 33,
    "name": "Expedita c",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 34,
    "name": "Voluptates sunt voluptas volu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 35,
    "name": "Autem mollitia fuga lauda",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 36,
    "name": "Sint quibusdam ob",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 37,
    "name": "Rerum et o",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 38,
    "name": "Doloribus dolore r",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 39,
    "name": "Eaque su",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 40,
    "name": "Vel molestias numqua",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 41,
    "name": "Iste assumenda repellat q",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 42,
    "name": "Animi labo",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 43,
    "name": "Eum culpa eaque ea omn",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 44,
    "name": "Harum provident vel quam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 45,
    "name": "Aspe",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 46,
    "name": "Nisi nequ",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 47,
    "name": "Quod tempora",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 48,
    "name": "Porro aliq",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 49,
    "name": "Quas",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 50,
    "name": "Magnam eligendi quia animi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 51,
    "name": "Officiis se",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 52,
    "name": "Id assumend",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 53,
    "name": "Voluptatibus fu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 54,
    "name": "Odit rat",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 55,
    "name": "Debit",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 56,
    "name": "Cum aut quas repudia",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 57,
    "name": "Deleniti qui quae quidem",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 58,
    "name": "Adipisci voluptas",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 59,
    "name": "Debitis sit ratione eos nam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 60,
    "name": "Esse illo molestias archi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 61,
    "name": "Sunt at itaque voluptatum d",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 62,
    "name": "Est totam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 63,
    "name": "Reprehenderit commodi eius",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 64,
    "name": "Debit",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 65,
    "name": "Soluta dol",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 66,
    "name": "Vel nesc",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 67,
    "name": "Ratione quia ali",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 68,
    "name": "Rerum recusandae minima",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 69,
    "name": "Totam natus eius fugiat volu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 70,
    "name": "Perferendis commodi null",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 71,
    "name": "Laudantiu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 72,
    "name": "Voluptat",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 73,
    "name": "Incidunt nesciun",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 74,
    "name": "Illum amet vero",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 75,
    "name": "Suscipit exercitationem re",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 76,
    "name": "Quas enim error maxime nisi m",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 77,
    "name": "Labore qu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 78,
    "name": "Repudiandae deleniti unde",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 79,
    "name": "Ut do",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 80,
    "name": "Quaerat esse labore q",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 81,
    "name": "Quidem aliq",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 82,
    "name": "Aperiam vitae eos dolor sed",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 83,
    "name": "Minus nobis porro",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 84,
    "name": "In similique",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 85,
    "name": "Culpa repellat unde",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 86,
    "name": "Architecto i",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 87,
    "name": "A sed pariatur qua",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 88,
    "name": "Tempore assumenda aperiam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 89,
    "name": "Sed ullam tempora iusto co",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 90,
    "name": "Ipsa",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 91,
    "name": "Fugiat incidun",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 92,
    "name": "Molestiae of",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 93,
    "name": "Quae quisquam cons",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 94,
    "name": "Repellendus ea non facil",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 95,
    "name": "Quod non quibu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 96,
    "name": "Numquam velit distinctio",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 97,
    "name": "Necessitatibus nihil ex debi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 98,
    "name": "Velit tempore nemo, na",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 99,
    "name": "Nesciunt v",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 100,
    "name": "Dicta enim debitis accusantiu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 101,
    "name": "Vitae a",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 102,
    "name": "Praesentium voluptas u",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 103,
    "name": "Unde ullam mollitia? Nu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 104,
    "name": "Neque molestias qu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 105,
    "name": "Officiis es",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 106,
    "name": "Beatae mi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 107,
    "name": "Mollitia nam corporis temp",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 108,
    "name": "Repudiandae repellat i",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 109,
    "name": "Laboriosam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 110,
    "name": "Nam minus amet",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 111,
    "name": "Harum quae volup",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 112,
    "name": "Impedit facere ulla",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 113,
    "name": "Enim",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 114,
    "name": "Dolore magni",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 115,
    "name": "Eaque at corpori",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 116,
    "name": "Fug",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 117,
    "name": "Dolorum laudanti",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 118,
    "name": "Perferendis nat",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 119,
    "name": "Cupidi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 120,
    "name": "Commodi eius dicta digniss",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 121,
    "name": "Debitis eu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 122,
    "name": "Nihil repella",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 123,
    "name": "Rem quasi minima hic sed anim",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 124,
    "name": "Sed ali",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 125,
    "name": "Earum vol",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 126,
    "name": "Inventore tempore com",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 127,
    "name": "Repell",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 128,
    "name": "Consequatur quis recusandae qu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 129,
    "name": "Dolores ea velit mi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 130,
    "name": "Atque blanditiis a aperiam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 131,
    "name": "Reprehenderit sequi iu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 132,
    "name": "Natus architecto eos, hic blan",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 133,
    "name": "Ipsa illo quas",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 134,
    "name": "Voluptas ali",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 135,
    "name": "Voluptates obcaecati quod e",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 136,
    "name": "Dolor adipisci a voluptate",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 137,
    "name": "Repellendus natus quae, n",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 138,
    "name": "Laudantium earum nam in dol",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 139,
    "name": "Molestias face",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 140,
    "name": "Maiores suscipit exc",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 141,
    "name": "Illum dolore perferen",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 142,
    "name": "Explicabo recusandae ma",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 143,
    "name": "Odio obcaecati hic nostrum n",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 144,
    "name": "Voluptate ali",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 145,
    "name": "Repudiandae vitae sapiente mol",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 146,
    "name": "Ipsam cumque",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 147,
    "name": "Fugiat quos alias eos dese",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 148,
    "name": "Eaque impe",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 149,
    "name": "Elige",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 150,
    "name": "Adip",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 151,
    "name": "Fuga nemo vel mo",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 152,
    "name": "Libero cumque impedit eveniet",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 153,
    "name": "Odio soluta",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 154,
    "name": "Vero nostrum duc",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 155,
    "name": "Repellend",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 156,
    "name": "Quod",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 157,
    "name": "Suscipit reiciend",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 158,
    "name": "Voluptat",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 159,
    "name": "Porro dolor fuga quam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 160,
    "name": "Amet quo fugit aliquam sequi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 161,
    "name": "Magni adipisci veritatis sit q",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 162,
    "name": "Debitis enim cumque cum qu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 163,
    "name": "Dolorem eligend",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 164,
    "name": "Autem lib",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 165,
    "name": "Saepe assumenda perferendis f",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 166,
    "name": "Deserunt",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 167,
    "name": "Provident soluta simil",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 168,
    "name": "In accu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 169,
    "name": "Inve",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 170,
    "name": "Placeat sapiente",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 171,
    "name": "Ducimus architecto ullam",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 172,
    "name": "Voluptate tempora rerum",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 173,
    "name": "Totam incidunt earum perspicia",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 174,
    "name": "Optio quas e",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 175,
    "name": "Ab illum invento",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 176,
    "name": "Repellat quis natus totam, s",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 177,
    "name": "Est voluptate accusantium tem",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 178,
    "name": "Beatae q",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 179,
    "name": "Velit",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 180,
    "name": "Minus nequ",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 181,
    "name": "Autem eos voluptates off",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 182,
    "name": "Vel fug",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 183,
    "name": "Architecto repudian",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 184,
    "name": "Opti",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 185,
    "name": "Iust",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 186,
    "name": "Sapiente",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 187,
    "name": "Officiis repellat corrupti su",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 188,
    "name": "Dicta et natus e",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 189,
    "name": "At quos",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 190,
    "name": "Laborum ven",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 191,
    "name": "Exceptur",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 192,
    "name": "Reiciendis assumenda dolo",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 193,
    "name": "Poss",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 194,
    "name": "Acc",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 195,
    "name": "Placeat esse archit",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 196,
    "name": "Enim repellendus nihil est te",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 197,
    "name": "Ipsam incidunt t",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 198,
    "name": "Iure",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 199,
    "name": "Illo en",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 200,
    "name": "A rem ex",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 201,
    "name": "Officiis su",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 202,
    "name": "Numquam molestias",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 203,
    "name": "Voluptates unde",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 204,
    "name": "Quae praesentium vel",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 205,
    "name": "Quas",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 206,
    "name": "Dolores aliquid inv",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 207,
    "name": "Mollitia tempore laborum eaqu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 208,
    "name": "Nobis voluptates fugiat quia",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 209,
    "name": "Similique dolorem dolore maio",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 210,
    "name": "Sapiente",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 211,
    "name": "Officia nisi dolore",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 212,
    "name": "Distinctio",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 213,
    "name": "Eos quia dignissimos saepe vel",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 214,
    "name": "Ullam neque sint eligendi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 215,
    "name": "Excepturi deleniti ab a",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 216,
    "name": "Accusa",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 217,
    "name": "Reiciendis laboriosam di",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 218,
    "name": "Delectus ex",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 219,
    "name": "Pari",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 220,
    "name": "Veritatis velit facilis iste",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 221,
    "name": "Dol",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 222,
    "name": "Qui iste pr",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 223,
    "name": "Deleni",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 224,
    "name": "Reprehenderit volu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 225,
    "name": "Accusantium vitae n",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 226,
    "name": "Natus consequatur incidun",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 227,
    "name": "Dignissimos a",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 228,
    "name": "Vitae modi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 229,
    "name": "Accusantium qu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 230,
    "name": "Reiciendis dignissimos ratio",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 231,
    "name": "Expedita provident natus volup",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 232,
    "name": "Rerum repellat voluptas c",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 233,
    "name": "Maiores quos incidunt dolor",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 234,
    "name": "Aper",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 235,
    "name": "Nulla",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 236,
    "name": "Laudantium tempora itaque",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 237,
    "name": "Reprehenderit",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 238,
    "name": "Aliqu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 239,
    "name": "Odio harum nam mole",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 240,
    "name": "Arc",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 241,
    "name": "Reprehenderit li",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 242,
    "name": "Repr",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 243,
    "name": "Optio m",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 244,
    "name": "Esse odit amet rep",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 245,
    "name": "Provident nostrum minima",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 246,
    "name": "Ex nihil quae facilis a omni",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 247,
    "name": "Dolorem quaerat sunt",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 248,
    "name": "Distinctio",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 249,
    "name": "Repudiandae ip",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 250,
    "name": "Iste debitis dolorum amet m",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 251,
    "name": "Non qui vo",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 252,
    "name": "Dolorem ma",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 253,
    "name": "Molestias labore tempore ita",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 254,
    "name": "Vol",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 255,
    "name": "Adipisci molest",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 256,
    "name": "Omni",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 257,
    "name": "Voluptatibus dolor",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 258,
    "name": "Quo",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 259,
    "name": "Atque aspernatur possi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 260,
    "name": "Ullam c",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 261,
    "name": "Iusto quas voluptatibu",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 262,
    "name": "Optio qui sunt dolores, ab",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 263,
    "name": "Illum recusandae nulla re",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 264,
    "name": "Verita",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 265,
    "name": "Expedita quod blanditiis",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 266,
    "name": "Mag",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 267,
    "name": "Omnis quos aspernatur d",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 268,
    "name": "Sunt impedit co",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 269,
    "name": "Minima quam ea ad",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 270,
    "name": "Suscipit quidem e",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 271,
    "name": "Harum",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 272,
    "name": "Dolore laborum ips",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 273,
    "name": "Magni veniam earum corporis",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 274,
    "name": "Optio",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 275,
    "name": "Nam fugit vel.",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 276,
    "name": "Ut numquam quam eum, alias ius",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 277,
    "name": "Error amet tempore nulla",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 278,
    "name": "Deserunt a",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 279,
    "name": "Aperiam sit",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 280,
    "name": "Asperi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 281,
    "name": "Similique aperiam earum expli",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 282,
    "name": "Iure h",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 283,
    "name": "At sint ducimus nostrum i",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 284,
    "name": "Reprehenderit temporib",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 285,
    "name": "Molestiae quaerat maxim",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 286,
    "name": "Maior",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 287,
    "name": "Unde natus ut ipsa cupi",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 288,
    "name": "Praesentium atque ear",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 289,
    "name": "Rem minima",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 290,
    "name": "Provident sed soluta, sed si",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 291,
    "name": "Natus quia veritatis",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 292,
    "name": "Vero a",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 293,
    "name": "Optio harum labori",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 294,
    "name": "Duci",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 295,
    "name": "Ipsa elige",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 296,
    "name": "Sunt blanditiis i",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 297,
    "name": "Doloremque",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 298,
    "name": "Autem ratione vitae quos, do",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 299,
    "name": "Voluptatibus aliquid",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 300,
    "name": "Quaerat sequi sit eius corpori",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 301,
    "name": "Libe",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  },
  {
    "character_id": 302,
    "name": "Aliquam n",
    "level": 0,
    "exp": 0,
    "hp": 10,
    "strength": 1,
    "intelligence": 1,
    "dexterity": 1,
    "wisdom": 1
  }
]

collection.insert_many(character_table)
print("DOCS:", collection.count_documents({}))
